# Generated by Django 5.0.7 on 2025-11-14 11:07

import django.db.models.deletion
import organization.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Organization name', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='About the organization')),
                ('logo', models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to=organization.models.organization_logo_upload_path)),
                ('cover_image', models.ImageField(blank=True, help_text='Organization banner/cover image', null=True, upload_to=organization.models.organization_cover_upload_path)),
                ('contact_email', models.EmailField(blank=True, help_text='Official contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('website', models.URLField(blank=True, help_text='Organization website', null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social media links (Facebook, Instagram, LinkedIn, Twitter, etc.)')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this organization is verified by admin')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this organization is active')),
                ('created_by', models.ForeignKey(help_text='User who created this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Gallery image', upload_to=organization.models.organization_gallery_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Image caption or description', max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
                ('organization', models.ForeignKey(help_text='Organization this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='organization.organization')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Gallery Image',
                'verbose_name_plural': 'Organization Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', help_text='Role of the member in the organization', max_length=10)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Custom permissions: can_create_events, can_edit_events, can_manage_members, etc.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is active')),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.organization')),
                ('user', models.ForeignKey(help_text='User who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_0d3b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_verified', 'is_active'], name='organizatio_is_veri_1c5b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationgallery',
            index=models.Index(fields=['organization', 'display_order'], name='organizatio_organiz_546158_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'user'], name='organizatio_organiz_33d05c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['role', 'is_active'], name='organizatio_role_f8ca35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
    ]
