# Generated by Django 5.0.7 on 2024-08-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEODetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/')),
                ('site_name', models.CharField(default='Gyan Aangan', max_length=255)),
            ],
        ),
    ]
