# Generated by Django 5.0.7 on 2024-08-04 13:59

import gyanaangan.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_seodetail_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seodetail',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=gyanaangan.settings.PublicMediaStorage, upload_to='og_images/'),
        ),
    ]
