# Generated by Django 5.0.7 on 2025-10-24 12:08

import django.utils.timezone
import gyanaangan.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seodetail_og_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for the banner (not displayed to users)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description or alt text for the banner', null=True)),
                ('image', models.ImageField(help_text='Banner image (recommended size: 1920x400px)', storage=gyanaangan.settings.PublicMediaStorage, upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-optimized image (recommended size: 768x300px)', null=True, storage=gyanaangan.settings.PublicMediaStorage, upload_to='banners/mobile/')),
                ('link_url', models.URLField(blank=True, help_text='Optional URL to redirect when banner is clicked', null=True)),
                ('link_text', models.CharField(blank=True, help_text="Optional call-to-action text (e.g., 'Learn More', 'Get Started')", max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary banner (only one should be primary at a time)')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle banner visibility')),
                ('active_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Banner will be visible from this date/time')),
                ('active_until', models.DateTimeField(help_text='Banner will be hidden after this date/time')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first (0 = highest priority)')),
                ('click_count', models.IntegerField(default=0, editable=False, help_text='Number of times this banner has been clicked')),
                ('view_count', models.IntegerField(default=0, editable=False, help_text='Number of times this banner has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order', '-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'active_from', 'active_until'], name='core_banner_is_acti_243581_idx'), models.Index(fields=['display_order', 'is_primary'], name='core_banner_display_f8b3c3_idx')],
            },
        ),
    ]
