# Generated by Django 5.0.7 on 2025-10-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='Banner will be hidden after this date/time (leave empty for no expiration)', null=True),
        ),
    ]
