# Generated by Django 5.0.7 on 2025-10-24 12:38

import gyanaangan.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_banner_active_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Banner image (recommended size: 1600x324px with aspect ratio 4.94:1)', storage=gyanaangan.settings.PublicMediaStorage, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='[DEPRECATED] Optional mobile image - Main image is now used for all devices', null=True, storage=gyanaangan.settings.PublicMediaStorage, upload_to='banners/mobile/'),
        ),
    ]
