# Generated by Django 5.0.7 on 2025-11-06 15:38

import gyanaangan.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_banner_image_alter_banner_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Desktop banner image (recommended size: 1600x324px with aspect ratio 4.94:1)', storage=gyanaangan.settings.PublicMediaStorage, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Mobile banner image (recommended size: 1600x648px - same width, double height)', null=True, storage=gyanaangan.settings.PublicMediaStorage, upload_to='banners/mobile/'),
        ),
    ]
