# Generated by Django 5.2.9 on 2026-05-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0026_subject_syllabus_text_alter_resource_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('groq', 'Groq'), ('openrouter', 'OpenRouter')], max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=255)),
                ('model_name', models.CharField(default='llama-3.1-70b-versatile', help_text='e.g. meta-llama/Llama-3-70b-chat-hf for OpenRouter', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one provider can be active at a time.')),
            ],
            options={
                'verbose_name': 'LLM Provider Config',
                'verbose_name_plural': 'LLM Provider Configs',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pyq_frequency', models.IntegerField(default=0)),
                ('marks_weight', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=1)),
                ('estimated_time', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.subject')),
            ],
        ),
        migrations.CreateModel(
            name='PYQTopicMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('marks_type', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=10)),
                ('weight', models.IntegerField(default=5)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='courses.resource')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topics.topic')),
            ],
        ),
    ]
