# Generated by Django 5.2.9 on 2026-05-07 18:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_subject_syllabus_text_alter_resource_file_and_more'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAIProxy',
            fields=[
            ],
            options={
                'verbose_name': 'PYQ AI Extraction',
                'verbose_name_plural': 'PYQ AI Extractions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.resource',),
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAIProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Subject AI Extraction',
                'verbose_name_plural': 'Subject AI Extractions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.subject',),
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
