# Generated by Django 5.0.7 on 2025-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscription_unique_together_studentprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_public',
            field=models.BooleanField(default=True, help_text="Whether the user's profile is publicly visible"),
        ),
    ]
