# Generated by Django 5.2.9 on 2026-09-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Analytics & Traffic',
                'verbose_name_plural': '📊 Blog Analytics & Traffic',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.blogpost',),
        ),
    ]
