# Generated by Django 5.0.7 on 2025-11-14 11:07

import django.db.models.deletion
import event.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=300, unique=True)),
                ('description', models.TextField(help_text='Detailed event description (supports rich text)')),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for preview cards', max_length=500)),
                ('event_type', models.CharField(choices=[('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('COMPETITION', 'Competition'), ('HACKATHON', 'Hackathon'), ('WEBINAR', 'Webinar'), ('CONFERENCE', 'Conference'), ('MEETUP', 'Meetup'), ('CULTURAL', 'Cultural Event'), ('SPORTS', 'Sports Event'), ('OTHER', 'Other')], default='OTHER', help_text='Type of event', max_length=20)),
                ('event_image', models.ImageField(blank=True, help_text='Event banner/poster image', null=True, upload_to=event.models.event_image_upload_path)),
                ('start_datetime', models.DateTimeField(help_text='Event start date and time')),
                ('end_datetime', models.DateTimeField(help_text='Event end date and time')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Last date to register (if different from event start)', null=True)),
                ('is_online', models.BooleanField(default=False, help_text='Is this an online event?')),
                ('venue_name', models.CharField(blank=True, help_text='Venue/Location name', max_length=255)),
                ('venue_address', models.TextField(blank=True, help_text='Full venue address')),
                ('google_maps_link', models.URLField(blank=True, help_text='Google Maps link for the venue', null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Meeting link for online events (Zoom, Meet, Teams, etc.)', null=True)),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum number of participants (leave blank for unlimited)', null=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Registration fee (0 for free events)', max_digits=10)),
                ('is_registration_open', models.BooleanField(default=True, help_text='Is registration currently open?')),
                ('prizes', models.JSONField(blank=True, default=dict, help_text='Prize information as JSON (e.g., {1st: 10000, 2nd: 5000})')),
                ('rules', models.TextField(blank=True, help_text='Event rules and regulations')),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Who can participate in this event')),
                ('schedule', models.JSONField(blank=True, default=list, help_text='Event schedule as JSON array')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Event tags for search and filtering')),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=255)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Event status', max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Is this event visible to public?')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured events appear prominently')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('created_by', models.ForeignKey(help_text='User who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization hosting this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(blank=True, help_text='Unique registration number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('WAITLIST', 'Waitlisted')], default='REGISTERED', help_text='Registration status', max_length=20)),
                ('attendance_status', models.CharField(choices=[('PENDING', 'Pending'), ('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PENDING', help_text='Attendance status', max_length=20)),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Custom form data (team name, special requirements, etc.)')),
                ('marked_present_at', models.DateTimeField(blank=True, help_text='When attendance was marked', null=True)),
                ('event', models.ForeignKey(help_text='Event for this registration', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='event.event')),
                ('marked_present_by', models.ForeignKey(blank=True, help_text='Organizer who marked attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who registered', on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name', max_length=255)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=15)),
                ('organization_name', models.CharField(blank=True, help_text='External organization/institution name', max_length=255)),
                ('designation', models.CharField(blank=True, help_text='Role/title/designation', max_length=255)),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', help_text='Attendance status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this participant')),
                ('added_by', models.ForeignKey(help_text='Organizer who added this participant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_manual_participants', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='Event this participant attended', on_delete=django.db.models.deletion.CASCADE, related_name='manual_participants', to='event.event')),
            ],
            options={
                'verbose_name': 'Manual Participant',
                'verbose_name_plural': 'Manual Participants',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='event_event_slug_8e22aa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'status'], name='event_event_organiz_3ef7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime', 'is_published'], name='event_event_start_d_7608e5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'is_published'], name='event_event_event_t_43a62e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='event_event_event_i_d73fee_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', 'status'], name='event_event_user_id_1a122c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['registration_number'], name='event_event_registr_7dd68c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='manualparticipant',
            index=models.Index(fields=['event', 'attendance_status'], name='event_manua_event_i_b7ccd1_idx'),
        ),
    ]
