# Generated by Django 5.0.7 on 2024-07-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.RemoveField(
            model_name='year',
            name='stream',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='years',
            field=models.ManyToManyField(related_name='courses', to='courses.year'),
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='streams',
            field=models.ManyToManyField(related_name='resources', to='courses.stream'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subjects',
            field=models.ManyToManyField(related_name='resources', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='stream',
            name='courses',
            field=models.ManyToManyField(related_name='streams', to='courses.course'),
        ),
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stream',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stream',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='stream',
            name='years',
            field=models.ManyToManyField(related_name='streams', to='courses.year'),
        ),
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(related_name='subjects', to='courses.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='streams',
            field=models.ManyToManyField(related_name='subjects', to='courses.stream'),
        ),
        migrations.AddField(
            model_name='subject',
            name='years',
            field=models.ManyToManyField(related_name='subjects', to='courses.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(),
        ),
    ]
