# Generated by Django 5.0.7 on 2024-07-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_advertisement_resource_course_resource_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='streams',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='years',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='years',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='streams',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='years',
        ),
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='common_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='common_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='common_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='courses.stream'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('pyq', 'Previous Year Question'), ('lab_manual', 'Lab Manual'), ('video', 'Video'), ('image', 'Image'), ('pdf', 'PDF')], db_index=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='educational_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.educationalyear'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='courses.subject'),
        ),
    ]
