# Generated by Django 5.0.7 on 2024-07-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_educationalyear_remove_resource_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='years',
            field=models.ManyToManyField(related_name='subjects', to='courses.year'),
        ),
    ]
