# Generated by Django 5.0.7 on 2024-07-16 15:23

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subject_last_resource_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='privacy',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('download', 'Download'), ('view', 'view')], default=['view'], max_length=13),
        ),
    ]
