# Generated by Django 5.0.7 on 2024-08-01 12:01

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_managers_alter_resource_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('tags', models.CharField(blank=True, choices=[('important', 'Important'), ('new', 'New'), ('update', 'Update'), ('info', 'Information')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('pyq', 'Previous Year Question'), ('lab manual', 'Lab Manual'), ('video', 'Video'), ('image', 'Image'), ('pdf', 'PDF')], db_index=True, max_length=20),
        ),
    ]
