# Generated by Django 5.0.7 on 2024-08-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_notification_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
