# Generated by Django 5.0.7 on 2024-08-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_notification_show_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='years',
            field=models.ManyToManyField(related_name='streams', to='courses.year'),
        ),
    ]
