# Generated by Django 5.0.7 on 2024-08-02 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_specialpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialpage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_page', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='specialpage',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_page', to='courses.stream'),
        ),
        migrations.AlterField(
            model_name='specialpage',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_page', to='courses.year'),
        ),
    ]
