# Generated by Django 5.0.7 on 2024-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_specialpage_course_alter_specialpage_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
        migrations.RemoveField(
            model_name='specialpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='og_image',
            field=models.FileField(blank=True, null=True, upload_to='og-image/'),
        ),
        migrations.AddField(
            model_name='course',
            name='og_image',
            field=models.FileField(blank=True, null=True, upload_to='og-image/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='og_image',
            field=models.FileField(blank=True, null=True, upload_to='og-image/'),
        ),
        migrations.AddField(
            model_name='specialpage',
            name='og_image',
            field=models.FileField(blank=True, null=True, upload_to='og-image/'),
        ),
        migrations.AddField(
            model_name='stream',
            name='og_image',
            field=models.FileField(blank=True, null=True, upload_to='og-image/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='og_image',
            field=models.FileField(blank=True, null=True, upload_to='og-image/'),
        ),
    ]
