# Generated by Django 5.0.7 on 2024-08-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_advertisement_og_image_alter_course_og_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='educationalyear',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='specialpage',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-updated_at']},
        ),
    ]
