# Generated by Django 5.2.9 on 2025-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_course_options_alter_resource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_link',
            field=models.URLField(blank=True, help_text='Direct link to external resource (PDF, document, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content for the resource (alternative to file/link)', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='embed_link',
            field=models.URLField(blank=True, help_text='For YouTube videos only', null=True),
        ),
    ]
