# Generated by Django 5.2.9 on 2025-12-06 13:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_add_resource_link_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rich text content for the resource (alternative to file/link)', null=True),
        ),
    ]
