# Generated by Django 5.2.9 on 2025-12-19 14:29

import gyanaangan.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_resource_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='original_file',
            field=models.FileField(blank=True, help_text='Backup of original file before watermarking', null=True, storage=gyanaangan.settings.PrivateMediaStorage, upload_to='resources/originals/'),
        ),
    ]
