# Generated by Django 5.2.9 on 2026-05-03 16:01

import ckeditor.fields
import gyanaangan.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_add_original_file_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rich text syllabus for AI topic extraction', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=gyanaangan.settings.PrivateMediaStorage, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='original_file',
            field=models.FileField(blank=True, help_text='Backup of original file before watermarking', max_length=500, null=True, storage=gyanaangan.settings.PrivateMediaStorage, upload_to='resources/originals/'),
        ),
    ]
