# Generated by Django 5.2.9 on 2026-05-12 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_subject_syllabus_text_alter_resource_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContentManagementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, related_name='managers', to='courses.course')),
                ('subjects', models.ManyToManyField(blank=True, related_name='managers', to='courses.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_management_permission', to=settings.AUTH_USER_MODEL)),
                ('years', models.ManyToManyField(blank=True, related_name='managers', to='courses.year')),
            ],
        ),
    ]
