# Generated by Django 5.2.9 on 2026-05-12 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_resource_uploaded_by_contentmanagementpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Sessional PYQ, Semester PYQ, Standard Notes', max_length=255, unique=True)),
                ('naming_convention', models.CharField(blank=True, help_text='e.g. [Subject] | [Year] | PYQ', max_length=500)),
                ('description_prompt', models.TextField(blank=True, help_text='Custom instructions for AI on description/keywords')),
            ],
        ),
        migrations.CreateModel(
            name='ContentManagementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_credit_user', models.ForeignKey(blank=True, help_text='Default user to assign upload credits to when a superuser bulk-uploads.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_credit_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Management Setting',
                'verbose_name_plural': 'Content Management Settings',
            },
        ),
    ]
