# Generated by Django 5.2.9 on 2026-05-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_aiprompttemplate_contentmanagementsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagementpermission',
            name='restricted_management',
            field=models.BooleanField(default=False, help_text='If enabled, this user can only upload new content and edit/delete resources they personally uploaded. They cannot modify content uploaded by other users.'),
        ),
    ]
