# Generated by Django 5.2.9 on 2025-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_visitor_device_brand_visitor_device_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='access_status',
            field=models.CharField(choices=[('allow', 'Allow'), ('force_login', 'Force Login'), ('block', 'Block')], default='allow', max_length=20),
        ),
    ]
