# Generated by Django 5.2.9 on 2026-09-28 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('courses', '0029_add_restricted_management_to_contentmanagementpermission'),
        ('tracking', '0003_visitor_access_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_slug', models.CharField(db_index=True, max_length=255)),
                ('total_views', models.PositiveIntegerField(db_index=True, default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('last_processed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Analytics',
                'verbose_name_plural': 'Blog Analytics',
                'ordering': ['-total_views'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_slug', models.CharField(db_index=True, max_length=255)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('total_views', models.PositiveIntegerField(db_index=True, default=0)),
                ('total_downloads', models.PositiveIntegerField(db_index=True, default=0)),
                ('total_engagement', models.PositiveIntegerField(db_index=True, default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('last_processed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resource Analytics',
                'verbose_name_plural': 'Resource Analytics',
                'ordering': ['-total_engagement', '-total_views'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_processed',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this event has been processed into analytics models'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_processed', 'event_type'], name='tracking_ev_is_proc_fcb516_idx'),
        ),
        migrations.AddField(
            model_name='bloganalytics',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_analytics', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='resourceanalytics',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_analytics', to='courses.resource'),
        ),
    ]
