# Generated by Django 5.2.9 on 2026-05-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studytask',
            new_name='planner_stu_plan_id_a10318_idx',
            old_name='planner_stu_plan_id_98ec4f_idx',
        ),
        migrations.RenameIndex(
            model_name='studytask',
            new_name='planner_stu_plan_id_966784_idx',
            old_name='planner_stu_plan_id_aecc13_idx',
        ),
    ]
